name: Build and Deploy to Github Pages

on:
  push:
    branches: [ "master" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    
    - name: Install dependencies
      run: |
        npm i -g hexo-cli
        npm i
    
    - name: Generate static files
      run: |
        hexo clean
        hexo g
    
    - name: Deploy to Github Pages
      env:
        GIT_NAME: lijinfeng
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        REPO: github.com/lijinfengnuc/lijinfengnuc.github.io
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        cd ./public && git init && git add .
        git config --global user.name $GIT_NAME
        git config --global user.email $GIT_EMAIL
        git commit -m "Site deployed by GitHub Actions"
        git push --force --quiet "https://$GH_TOKEN@$REPO" master:master
